name: CI
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:


jobs:
  linter-and-license:
    name: Linter & License Check
    runs-on: ubuntu-22.04
    container: ghcr.io/jaxtonmax/hvisor-ci:22.04_pro
    steps:
      - name: Reset Rustup to Official Servers
        run: |
          echo "RUSTUP_DIST_SERVER=https://static.rust-lang.org" >> $GITHUB_ENV
          echo "RUSTUP_UPDATE_ROOT=https://static.rust-lang.org/rustup" >> $GITHUB_ENV
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Format Check
        run: make fmt-test
      - name: License Check
        run: ./tools/license_checker.sh

  unittest:
    name: Unittest
    runs-on: ubuntu-22.04
    container: ghcr.io/jaxtonmax/hvisor-ci:22.04_pro
    strategy:
      fail-fast: false
      matrix:
        include:
          - { arch: aarch64, board: "qemu-gicv3" }
          - { arch: aarch64, board: "qemu-gicv2" }
          - { arch: riscv64, board: "qemu-plic" }
          - { arch: riscv64, board: "qemu-aia" }
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Reset Rustup to Official Servers
        run: |
          echo "RUSTUP_DIST_SERVER=https://static.rust-lang.org" >> $GITHUB_ENV
          echo "RUSTUP_UPDATE_ROOT=https://static.rust-lang.org/rustup" >> $GITHUB_ENV
      - name: Set up environment variables
        run: |
          echo "ARCH=${{ matrix.arch }}" >> $GITHUB_ENV
          echo "BOARD=${{ matrix.board }}" >> $GITHUB_ENV
      - name: Run Unit Test
        # 所有依赖已在镜像中，直接运行测试
        run: make test

  build:
    name: Build All Targets
    runs-on: ubuntu-22.04
    container: ghcr.io/jaxtonmax/hvisor-ci:22.04_pro
    strategy:
      fail-fast: false
      matrix:
        include:
          - { arch: aarch64, board: "qemu-gicv3" }
          - { arch: aarch64, board: "qemu-gicv2" }
          - { arch: aarch64, board: "zcu102" }
          - { arch: aarch64, board: "imx8mp" }
          - { arch: aarch64, board: "rk3568" }
          - { arch: aarch64, board: "rk3588" }
          - { arch: aarch64, board: "ok6254-c" }
          - { arch: riscv64, board: "qemu-aia" }
          - { arch: riscv64, board: "qemu-plic" }
          # LoongArch 构建任务也在这里
          - { arch: loongarch64, board: "ls3a5000" }
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Reset Rustup to Official Servers
        run: |
          echo "RUSTUP_DIST_SERVER=https://static.rust-lang.org" >> $GITHUB_ENV
          echo "RUSTUP_UPDATE_ROOT=https://static.rust-lang.org/rustup" >> $GITHUB_ENV

      # --- 关键优化：为 LoongArch 动态加载工具链 ---
      - name: Cache and Install LoongArch Toolchain
        if: matrix.arch == 'loongarch64'
        uses: actions/cache@v4
        with:
          # 需要缓存的目录
          path: /opt/loongarch-toolchain
          # 缓存的唯一标识，如果工具链更新，可以修改这个 key 来刷新缓存
          key: ${{ runner.os }}-loongarch-toolchain-v8.0
      
      - name: Download LoongArch Toolchain if not cached
        if: matrix.arch == 'loongarch64' && steps.cache-loongarch.outputs.cache-hit != 'true'
        run: |
          mkdir -p /opt/loongarch-toolchain
          wget -qO- https://github.com/sunhaiyong1978/CLFS-for-LoongArch/releases/download/8.0/loongarch64-clfs-8.0-cross-tools-gcc-full.tar.xz | tar -xJ -C /opt/loongarch-toolchain

      - name: Add LoongArch Toolchain to PATH
        if: matrix.arch == 'loongarch64'
        run: echo "/opt/loongarch-toolchain/cross-tools/bin" >> $GITHUB_PATH
      
      # --- 核心构建步骤 ---
      - name: Set up environment variables
        run: |
          echo "ARCH=${{ matrix.arch }}" >> $GITHUB_ENV
          echo "BOARD=${{ matrix.board }}" >> $GITHUB_ENV
      - name: Build
        run: make

  systemtest:
    name: Systemtest
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/jaxtonmax/hvisor-ci:22.04_pro
      options: --cap-add=SYS_ADMIN --privileged
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64
            rustc_target: aarch64-unknown-none
            board: "qemu-gicv3"
          - arch: riscv64
            rustc_target: riscv64gc-unknown-none-elf
            board: "qemu-plic"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Reset Rustup to Official Servers
        run: |
          echo "RUSTUP_DIST_SERVER=https://static.rust-lang.org" >> $GITHUB_ENV
          echo "RUSTUP_UPDATE_ROOT=https://static.rust-lang.org/rustup" >> $GITHUB_ENV

      - name: Set up environment variables
        run: |
          echo "ARCH=${{ matrix.arch }}" >> $GITHUB_ENV
          echo "BOARD=${{ matrix.board }}" >> $GITHUB_ENV

      - name: Run System Test
        run: |
          # 设置架构特定的编译环境
          case "${{ matrix.arch }}" in
            riscv64)
              export SYSROOT_PATH="/usr/riscv64-linux-gnu"
              export CROSS_PREFIX="riscv64-linux-gnu-"
              ;;
            aarch64)
              export SYSROOT_PATH="/usr/aarch64-linux-gnu"
              export CROSS_PREFIX="aarch64-linux-gnu-"
              ;;
          esac

          # 强制设置所有必要的编译变量
          export CC="${CROSS_PREFIX}gcc"
          export CXX="${CROSS_PREFIX}g++"
          export AR="${CROSS_PREFIX}ar"
          export LD="${CROSS_PREFIX}ld"
          
          # 关键修复：同时设置 CFLAGS 和 CPPFLAGS
          export CFLAGS="--sysroot=${SYSROOT_PATH} -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0"
          export CPPFLAGS="-I${SYSROOT_PATH}/include"
          export LDFLAGS="-L${SYSROOT_PATH}/lib -Wl,-rpath-link,${SYSROOT_PATH}/lib"
          
          # 递归传递变量给所有子make
          export MAKE="make -e"
          
          # 显示环境变量用于调试
          echo "=== Build Environment ==="
          echo "CC=$CC"
          echo "CFLAGS=$CFLAGS"
          echo "CPPFLAGS=$CPPFLAGS"
          echo "LDFLAGS=$LDFLAGS"
          echo "MAKE=$MAKE"
          
          # 执行构建
          make -e stest